version: 2.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:21.0  # Use Java 21 image

    steps:
      - checkout  # Checkout the code from your repository

      - run:
          name: Download JUnit and Hamcrest JARs
          command: |
            curl -L -o junit-4.13.2.jar https://repo1.maven.org/maven2/junit/junit/4.13.2/junit-4.13.2.jar
            curl -L -o hamcrest-core-1.3.jar https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar

      - run:
          name: Compile Java Tests
          command: |
            mkdir -p bin
            javac -d bin -cp .:junit-4.13.2.jar:hamcrest-core-1.3.jar src/*.java  # Compile Java files into bin folder

      - run:
          name: Run JUnit Tests with Detailed Output
          command: |
            mkdir -p test-results  # Create directory for test results
            java -cp bin:junit-4.13.2.jar:hamcrest-core-1.3.jar \
              org.junit.runner.JUnitCore BoardTest \
              | tee test-results/output.txt  # Capture output

      # Store test results as artifacts so you can see detailed reports in CircleCI
      - store_artifacts:
          path: test-results/output.txt
          destination: junit-output

      # Save the test results for later inspection in the CircleCI UI
      - store_test_results:
          path: test-results

workflows:
  version: 2
  test-workflow:
    jobs:
      - test
