version: 2.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:21.0  # Java 21 Docker image

    steps:
      - checkout  # Checkout the code from your repository

      # Compile and run your Java test file
      - run:
          name: Compile and test
          command: |
            javac test.java  # Replace 'test.java' with your actual Java test file name
            java test  # Replace 'test' with the main class name if applicable

workflows:
  version: 2
  test-workflow:
    jobs:
      - test
