version: 2.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:21.0  # Java 21 Docker image

    steps:
      - checkout  # Checkout the code from your repository

      # Compile and run your Java test file
      - run:
          name: Compile and test
          command: |
            javac BoardTest.java  
            java test 

workflows:
  version: 2
  test-workflow:
    jobs:
      - test
